# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('zilla', models.CharField(max_length=100)),
                ('upazilla', models.CharField(max_length=100)),
                ('mouja', models.CharField(max_length=100)),
                ('dag_no', models.IntegerField()),
                ('catagory', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('up_for_sale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('tax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Land')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='roles',
            name='roles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lands.User'),
        ),
        migrations.AddField(
            model_name='land',
            name='owners',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lands.User'),
        ),
    ]
