# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.User')),
            ],
        ),
    ]
