# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_userland'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='owners',
        ),
        migrations.AddField(
            model_name='land',
            name='owners',
            field=models.ManyToManyField(to='lands.User'),
        ),
    ]
